// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: inference.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_ExtractLineArt_FullMethodName   = "/animecraft.inference.InferenceService/ExtractLineArt"
	InferenceService_GenerateFeedback_FullMethodName = "/animecraft.inference.InferenceService/GenerateFeedback"
	InferenceService_HealthCheck_FullMethodName      = "/animecraft.inference.InferenceService/HealthCheck"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	// ExtractLineArt converts a reference image to grayscale line art.
	ExtractLineArt(ctx context.Context, in *ExtractLineArtRequest, opts ...grpc.CallOption) (*ExtractLineArtResponse, error)
	// GenerateFeedback compares reference line art with a user's drawing
	// and streams structured feedback token-by-token.
	GenerateFeedback(ctx context.Context, in *GenerateFeedbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateFeedbackResponse], error)
	// HealthCheck reports whether the service and its models are loaded.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) ExtractLineArt(ctx context.Context, in *ExtractLineArtRequest, opts ...grpc.CallOption) (*ExtractLineArtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractLineArtResponse)
	err := c.cc.Invoke(ctx, InferenceService_ExtractLineArt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) GenerateFeedback(ctx context.Context, in *GenerateFeedbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateFeedbackResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], InferenceService_GenerateFeedback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateFeedbackRequest, GenerateFeedbackResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateFeedbackClient = grpc.ServerStreamingClient[GenerateFeedbackResponse]

func (c *inferenceServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InferenceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
type InferenceServiceServer interface {
	// ExtractLineArt converts a reference image to grayscale line art.
	ExtractLineArt(context.Context, *ExtractLineArtRequest) (*ExtractLineArtResponse, error)
	// GenerateFeedback compares reference line art with a user's drawing
	// and streams structured feedback token-by-token.
	GenerateFeedback(*GenerateFeedbackRequest, grpc.ServerStreamingServer[GenerateFeedbackResponse]) error
	// HealthCheck reports whether the service and its models are loaded.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) ExtractLineArt(context.Context, *ExtractLineArtRequest) (*ExtractLineArtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractLineArt not implemented")
}
func (UnimplementedInferenceServiceServer) GenerateFeedback(*GenerateFeedbackRequest, grpc.ServerStreamingServer[GenerateFeedbackResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateFeedback not implemented")
}
func (UnimplementedInferenceServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_ExtractLineArt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractLineArtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ExtractLineArt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_ExtractLineArt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ExtractLineArt(ctx, req.(*ExtractLineArtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_GenerateFeedback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateFeedbackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServiceServer).GenerateFeedback(m, &grpc.GenericServerStream[GenerateFeedbackRequest, GenerateFeedbackResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateFeedbackServer = grpc.ServerStreamingServer[GenerateFeedbackResponse]

func _InferenceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "animecraft.inference.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractLineArt",
			Handler:    _InferenceService_ExtractLineArt_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InferenceService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateFeedback",
			Handler:       _InferenceService_GenerateFeedback_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}
