// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractLineArtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractLineArtRequest) Reset() {
	*x = ExtractLineArtRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractLineArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLineArtRequest) ProtoMessage() {}

func (x *ExtractLineArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLineArtRequest.ProtoReflect.Descriptor instead.
func (*ExtractLineArtRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractLineArtRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type ExtractLineArtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineArtPng    []byte                 `protobuf:"bytes,1,opt,name=line_art_png,json=lineArtPng,proto3" json:"line_art_png,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractLineArtResponse) Reset() {
	*x = ExtractLineArtResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractLineArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLineArtResponse) ProtoMessage() {}

func (x *ExtractLineArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLineArtResponse.ProtoReflect.Descriptor instead.
func (*ExtractLineArtResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractLineArtResponse) GetLineArtPng() []byte {
	if x != nil {
		return x.LineArtPng
	}
	return nil
}

type GenerateFeedbackRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReferenceLineArtPng []byte                 `protobuf:"bytes,1,opt,name=reference_line_art_png,json=referenceLineArtPng,proto3" json:"reference_line_art_png,omitempty"`
	DrawingPng          []byte                 `protobuf:"bytes,2,opt,name=drawing_png,json=drawingPng,proto3" json:"drawing_png,omitempty"`
	ExerciseMode        string                 `protobuf:"bytes,3,opt,name=exercise_mode,json=exerciseMode,proto3" json:"exercise_mode,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateFeedbackRequest) Reset() {
	*x = GenerateFeedbackRequest{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedbackRequest) ProtoMessage() {}

func (x *GenerateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GenerateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateFeedbackRequest) GetReferenceLineArtPng() []byte {
	if x != nil {
		return x.ReferenceLineArtPng
	}
	return nil
}

func (x *GenerateFeedbackRequest) GetDrawingPng() []byte {
	if x != nil {
		return x.DrawingPng
	}
	return nil
}

func (x *GenerateFeedbackRequest) GetExerciseMode() string {
	if x != nil {
		return x.ExerciseMode
	}
	return ""
}

type GenerateFeedbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GenerateFeedbackResponse_TextChunk
	//	*GenerateFeedbackResponse_Result
	Payload       isGenerateFeedbackResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFeedbackResponse) Reset() {
	*x = GenerateFeedbackResponse{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedbackResponse) ProtoMessage() {}

func (x *GenerateFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedbackResponse.ProtoReflect.Descriptor instead.
func (*GenerateFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateFeedbackResponse) GetPayload() isGenerateFeedbackResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GenerateFeedbackResponse) GetTextChunk() string {
	if x != nil {
		if x, ok := x.Payload.(*GenerateFeedbackResponse_TextChunk); ok {
			return x.TextChunk
		}
	}
	return ""
}

func (x *GenerateFeedbackResponse) GetResult() *FeedbackResult {
	if x != nil {
		if x, ok := x.Payload.(*GenerateFeedbackResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isGenerateFeedbackResponse_Payload interface {
	isGenerateFeedbackResponse_Payload()
}

type GenerateFeedbackResponse_TextChunk struct {
	TextChunk string `protobuf:"bytes,1,opt,name=text_chunk,json=textChunk,proto3,oneof"`
}

type GenerateFeedbackResponse_Result struct {
	Result *FeedbackResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*GenerateFeedbackResponse_TextChunk) isGenerateFeedbackResponse_Payload() {}

func (*GenerateFeedbackResponse_Result) isGenerateFeedbackResponse_Payload() {}

type FeedbackResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OverallScore     int32                  `protobuf:"varint,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	ProportionsScore int32                  `protobuf:"varint,2,opt,name=proportions_score,json=proportionsScore,proto3" json:"proportions_score,omitempty"`
	LineQualityScore int32                  `protobuf:"varint,3,opt,name=line_quality_score,json=lineQualityScore,proto3" json:"line_quality_score,omitempty"`
	AccuracyScore    int32                  `protobuf:"varint,4,opt,name=accuracy_score,json=accuracyScore,proto3" json:"accuracy_score,omitempty"`
	Summary          string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Details          string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	Strengths        []string               `protobuf:"bytes,7,rep,name=strengths,proto3" json:"strengths,omitempty"`
	Improvements     []string               `protobuf:"bytes,8,rep,name=improvements,proto3" json:"improvements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeedbackResult) Reset() {
	*x = FeedbackResult{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResult) ProtoMessage() {}

func (x *FeedbackResult) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResult.ProtoReflect.Descriptor instead.
func (*FeedbackResult) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *FeedbackResult) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *FeedbackResult) GetProportionsScore() int32 {
	if x != nil {
		return x.ProportionsScore
	}
	return 0
}

func (x *FeedbackResult) GetLineQualityScore() int32 {
	if x != nil {
		return x.LineQualityScore
	}
	return 0
}

func (x *FeedbackResult) GetAccuracyScore() int32 {
	if x != nil {
		return x.AccuracyScore
	}
	return 0
}

func (x *FeedbackResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FeedbackResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *FeedbackResult) GetStrengths() []string {
	if x != nil {
		return x.Strengths
	}
	return nil
}

func (x *FeedbackResult) GetImprovements() []string {
	if x != nil {
		return x.Improvements
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineArtReady  bool                   `protobuf:"varint,1,opt,name=line_art_ready,json=lineArtReady,proto3" json:"line_art_ready,omitempty"`
	FeedbackReady bool                   `protobuf:"varint,2,opt,name=feedback_ready,json=feedbackReady,proto3" json:"feedback_ready,omitempty"`
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetLineArtReady() bool {
	if x != nil {
		return x.LineArtReady
	}
	return false
}

func (x *HealthCheckResponse) GetFeedbackReady() bool {
	if x != nil {
		return x.FeedbackReady
	}
	return false
}

func (x *HealthCheckResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x14animecraft.inference\"6\n" +
	"\x15ExtractLineArtRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\":\n" +
	"\x16ExtractLineArtResponse\x12 \n" +
	"\fline_art_png\x18\x01 \x01(\fR\n" +
	"lineArtPng\"\x94\x01\n" +
	"\x17GenerateFeedbackRequest\x123\n" +
	"\x16reference_line_art_png\x18\x01 \x01(\fR\x13referenceLineArtPng\x12\x1f\n" +
	"\vdrawing_png\x18\x02 \x01(\fR\n" +
	"drawingPng\x12#\n" +
	"\rexercise_mode\x18\x03 \x01(\tR\fexerciseMode\"\x86\x01\n" +
	"\x18GenerateFeedbackResponse\x12\x1f\n" +
	"\n" +
	"text_chunk\x18\x01 \x01(\tH\x00R\ttextChunk\x12>\n" +
	"\x06result\x18\x02 \x01(\v2$.animecraft.inference.FeedbackResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xad\x02\n" +
	"\x0eFeedbackResult\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x05R\foverallScore\x12+\n" +
	"\x11proportions_score\x18\x02 \x01(\x05R\x10proportionsScore\x12,\n" +
	"\x12line_quality_score\x18\x03 \x01(\x05R\x10lineQualityScore\x12%\n" +
	"\x0eaccuracy_score\x18\x04 \x01(\x05R\raccuracyScore\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\x12\x1c\n" +
	"\tstrengths\x18\a \x03(\tR\tstrengths\x12\"\n" +
	"\fimprovements\x18\b \x03(\tR\fimprovements\"\x14\n" +
	"\x12HealthCheckRequest\"\x89\x01\n" +
	"\x13HealthCheckResponse\x12$\n" +
	"\x0eline_art_ready\x18\x01 \x01(\bR\flineArtReady\x12%\n" +
	"\x0efeedback_ready\x18\x02 \x01(\bR\rfeedbackReady\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage2\xd8\x02\n" +
	"\x10InferenceService\x12k\n" +
	"\x0eExtractLineArt\x12+.animecraft.inference.ExtractLineArtRequest\x1a,.animecraft.inference.ExtractLineArtResponse\x12s\n" +
	"\x10GenerateFeedback\x12-.animecraft.inference.GenerateFeedbackRequest\x1a..animecraft.inference.GenerateFeedbackResponse0\x01\x12b\n" +
	"\vHealthCheck\x12(.animecraft.inference.HealthCheckRequest\x1a).animecraft.inference.HealthCheckResponseBFZDgithub.com/michael-freling/anime-craft/gateway/internal/inference/pbb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inference_proto_goTypes = []any{
	(*ExtractLineArtRequest)(nil),    // 0: animecraft.inference.ExtractLineArtRequest
	(*ExtractLineArtResponse)(nil),   // 1: animecraft.inference.ExtractLineArtResponse
	(*GenerateFeedbackRequest)(nil),  // 2: animecraft.inference.GenerateFeedbackRequest
	(*GenerateFeedbackResponse)(nil), // 3: animecraft.inference.GenerateFeedbackResponse
	(*FeedbackResult)(nil),           // 4: animecraft.inference.FeedbackResult
	(*HealthCheckRequest)(nil),       // 5: animecraft.inference.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 6: animecraft.inference.HealthCheckResponse
}
var file_inference_proto_depIdxs = []int32{
	4, // 0: animecraft.inference.GenerateFeedbackResponse.result:type_name -> animecraft.inference.FeedbackResult
	0, // 1: animecraft.inference.InferenceService.ExtractLineArt:input_type -> animecraft.inference.ExtractLineArtRequest
	2, // 2: animecraft.inference.InferenceService.GenerateFeedback:input_type -> animecraft.inference.GenerateFeedbackRequest
	5, // 3: animecraft.inference.InferenceService.HealthCheck:input_type -> animecraft.inference.HealthCheckRequest
	1, // 4: animecraft.inference.InferenceService.ExtractLineArt:output_type -> animecraft.inference.ExtractLineArtResponse
	3, // 5: animecraft.inference.InferenceService.GenerateFeedback:output_type -> animecraft.inference.GenerateFeedbackResponse
	6, // 6: animecraft.inference.InferenceService.HealthCheck:output_type -> animecraft.inference.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	file_inference_proto_msgTypes[3].OneofWrappers = []any{
		(*GenerateFeedbackResponse_TextChunk)(nil),
		(*GenerateFeedbackResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
